"""Initial migration with all core tables

Revision ID: 187516e3676e
Revises: 
Create Date: 2025-11-14 09:57:31.869600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '187516e3676e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    op.create_table('strategies',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategies_id'), 'strategies', ['id'], unique=False)
    op.create_index(op.f('ix_strategies_name'), 'strategies', ['name'], unique=True)
    op.create_table('indicators',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('indicator_name', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_id'), 'indicators', ['id'], unique=False)
    op.create_index(op.f('ix_indicators_indicator_name'), 'indicators', ['indicator_name'], unique=False)
    op.create_index(op.f('ix_indicators_stock_id'), 'indicators', ['stock_id'], unique=False)
    op.create_index(op.f('ix_indicators_timestamp'), 'indicators', ['timestamp'], unique=False)
    op.create_table('stock_data',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_data_id'), 'stock_data', ['id'], unique=False)
    op.create_index(op.f('ix_stock_data_stock_id'), 'stock_data', ['stock_id'], unique=False)
    op.create_index(op.f('ix_stock_data_timestamp'), 'stock_data', ['timestamp'], unique=False)
    op.create_table('strategy_events',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_events_event_type'), 'strategy_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_strategy_events_id'), 'strategy_events', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_events_strategy_id'), 'strategy_events', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_strategy_events_timestamp'), 'strategy_events', ['timestamp'], unique=False)
    op.create_table('trade_signals',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('signal_type', sa.String(length=20), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=True),
    sa.Column('indicator_values', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_signals_id'), 'trade_signals', ['id'], unique=False)
    op.create_index(op.f('ix_trade_signals_signal_time'), 'trade_signals', ['signal_time'], unique=False)
    op.create_index(op.f('ix_trade_signals_stock_id'), 'trade_signals', ['stock_id'], unique=False)
    op.create_index(op.f('ix_trade_signals_strategy_id'), 'trade_signals', ['strategy_id'], unique=False)
    op.create_table('trades',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_loss', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('profit_loss_percent', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('market_context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_entry_time'), 'trades', ['entry_time'], unique=False)
    op.create_index(op.f('ix_trades_exit_time'), 'trades', ['exit_time'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_index(op.f('ix_trades_stock_id'), 'trades', ['stock_id'], unique=False)
    op.create_index(op.f('ix_trades_strategy_id'), 'trades', ['strategy_id'], unique=False)
    op.create_table('orders',
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('limit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('filled_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_order_id'), 'orders', ['broker_order_id'], unique=True)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_stock_id'), 'orders', ['stock_id'], unique=False)
    op.create_index(op.f('ix_orders_trade_id'), 'orders', ['trade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_trade_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_stock_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_trades_strategy_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_stock_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exit_time'), table_name='trades')
    op.drop_index(op.f('ix_trades_entry_time'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_trade_signals_strategy_id'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_stock_id'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_signal_time'), table_name='trade_signals')
    op.drop_index(op.f('ix_trade_signals_id'), table_name='trade_signals')
    op.drop_table('trade_signals')
    op.drop_index(op.f('ix_strategy_events_timestamp'), table_name='strategy_events')
    op.drop_index(op.f('ix_strategy_events_strategy_id'), table_name='strategy_events')
    op.drop_index(op.f('ix_strategy_events_id'), table_name='strategy_events')
    op.drop_index(op.f('ix_strategy_events_event_type'), table_name='strategy_events')
    op.drop_table('strategy_events')
    op.drop_index(op.f('ix_stock_data_timestamp'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_stock_id'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_id'), table_name='stock_data')
    op.drop_table('stock_data')
    op.drop_index(op.f('ix_indicators_timestamp'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_stock_id'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_indicator_name'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_id'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_strategies_name'), table_name='strategies')
    op.drop_index(op.f('ix_strategies_id'), table_name='strategies')
    op.drop_table('strategies')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    # ### end Alembic commands ###
