"""Add backtest tables for Phase 4

Revision ID: 3251f293a6fe
Revises: 187516e3676e
Create Date: 2025-11-17 14:17:23.417872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3251f293a6fe'
down_revision: Union[str, None] = '187516e3676e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backtest_runs',
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('commission_per_trade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('strategy_parameters', sa.JSON(), nullable=False),
    sa.Column('final_equity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_return_pct', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('annualized_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('win_rate_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('losing_trades', sa.Integer(), nullable=True),
    sa.Column('avg_win', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('avg_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('largest_win', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('largest_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('execution_time_seconds', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bars_processed', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'stock_id', 'start_date', 'end_date', name='uq_backtest_run')
    )
    op.create_index(op.f('ix_backtest_runs_id'), 'backtest_runs', ['id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_stock_id'), 'backtest_runs', ['stock_id'], unique=False)
    op.create_index(op.f('ix_backtest_runs_strategy_id'), 'backtest_runs', ['strategy_id'], unique=False)
    op.create_table('backtest_equity_curve',
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cash', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('position_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('daily_return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('drawdown_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('backtest_run_id', 'date', name='uq_backtest_equity_date')
    )
    op.create_index(op.f('ix_backtest_equity_curve_backtest_run_id'), 'backtest_equity_curve', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_equity_curve_date'), 'backtest_equity_curve', ['date'], unique=False)
    op.create_index(op.f('ix_backtest_equity_curve_id'), 'backtest_equity_curve', ['id'], unique=False)
    op.create_table('backtest_trades',
    sa.Column('backtest_run_id', sa.Integer(), nullable=False),
    sa.Column('trade_number', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('entry_signal', sa.String(length=20), nullable=False),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('exit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('exit_signal', sa.String(length=20), nullable=True),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('position_value', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('gross_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('commission_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('slippage_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_pnl', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('return_pct', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('holding_period_days', sa.Integer(), nullable=True),
    sa.Column('is_winner', sa.Boolean(), nullable=True),
    sa.Column('entry_indicators', sa.JSON(), nullable=True),
    sa.Column('entry_market_context', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['backtest_run_id'], ['backtest_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_backtest_run_id'), 'backtest_trades', ['backtest_run_id'], unique=False)
    op.create_index(op.f('ix_backtest_trades_id'), 'backtest_trades', ['id'], unique=False)
    op.add_column('strategies', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('strategies', sa.Column('warm_up_bars_remaining', sa.Integer(), nullable=False))
    op.add_column('trade_signals', sa.Column('market_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_signals', 'market_context')
    op.drop_column('strategies', 'warm_up_bars_remaining')
    op.drop_column('strategies', 'status')
    op.drop_index(op.f('ix_backtest_trades_id'), table_name='backtest_trades')
    op.drop_index(op.f('ix_backtest_trades_backtest_run_id'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_index(op.f('ix_backtest_equity_curve_id'), table_name='backtest_equity_curve')
    op.drop_index(op.f('ix_backtest_equity_curve_date'), table_name='backtest_equity_curve')
    op.drop_index(op.f('ix_backtest_equity_curve_backtest_run_id'), table_name='backtest_equity_curve')
    op.drop_table('backtest_equity_curve')
    op.drop_index(op.f('ix_backtest_runs_strategy_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_stock_id'), table_name='backtest_runs')
    op.drop_index(op.f('ix_backtest_runs_id'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    # ### end Alembic commands ###
